export { default as Header } from './Header/Header'
export { default as Parnter } from './Parnter/Parnter'
export { default as Panel } from './Panel/Panel'
export { default as People } from './People/People'
export { default as World } from './World/World'
export { default as BOx } from './Box/BOx'
export { default as Hero } from './Hero/Hero'
export { default as Mission } from './Mission/Mission'
export { default as Casestudy } from './Casestudy/Casestudy'
export { default as Item } from './Item/Item'
export { default as CasestudyDetails } from './CasestudyDetails/CasestudyDetails'
export {default as ServiceHeader} from './Service/ServicesHeader/ServiceHeader'
export {default as ServiceInnovation} from './Service/ServiceInnovation/ServiceInnovation'
export {default as ServiceWork} from './Service/ServiceWork/ServiceWork'
export {default as ServiceAbout} from './Service/ServiceAbout/ServiceAbout'
export {default as ServiceFooter} from './Service/ServiceFooter/ServiceFooter'
export {default as JoinHeader} from './Join/JoinHeader/JoinHeader'
export {default as JoinService} from './Join/JoinService/JoinService'
export {default as JoinApplication} from './Join/JoinApplication/JoinApplication'
export {default as Start} from './Join/Start/Start'
export {default as Current} from './Join/Current/Current'
export {default as ApplyForm} from './Join/ApplyForm/ApplyForm'