export {default as Navbar} from './Navbar/Navbar'
export{default as Brand} from './Brand/Brand'
export {default as Footer} from './Footer/Footer'
export {default as CTA} from './CTA/CTA'
export {default as Connect} from './Connect/Connect'
export {default as Gallery} from './Gallery/Gallery'
export {default as Termional} from './Termional/Termional'
export {default as Category} from './Category/Category'
export {default as Pagination} from './Pagination/Pagination'
export {default as ScrollToTopButton} from './ScrollToTopButton/ScrollToTopButton '