export { default as Home } from './Home/Home'
export { default as Services } from './Services/Services'
export { default as Join } from './Join/Join'
export { default as Blog } from './Blog/Blog'
export { default as About } from './About/About'
export {default as Contact} from './Contact/Contact'
export {default as VisitCard} from './VisitCard/VisitCard'